working unmemoization and full or partial cache clearing

diff --git a/zsh/functions/zmemoize b/zsh/functions/zmemoize
--- a/zsh/functions/zmemoize
+++ b/zsh/functions/zmemoize
@@ -40,17 +40,22 @@
 ##        ZSH option settings; option names are expressed as space or comma separated
 ##        names in string form, e.g. "login,promptpercent"
 ##
-##    -h
+##    -H
 ##        Hostname.  Set by default. May be disabled with "+h".
 ##
 ##    -u
 ##        Username.  Set by default. May be disabled with "+u".
 ##
 
+typeset -g -H -A zmemoize_config
+typeset -g -H -A zmemoize_defs
+typeset -g -H -A zmemoize_cache
 
 function _zmemoize_calculate_key {
   emulate -L zsh
-  echo ${(pj:\0:)*}
+  local funcname=$1
+  shift
+  echo "${funcname}:${(pj:\0:)*}"
 }
 
 function _zmemoize_capture {
@@ -84,7 +89,11 @@ function _zmemoize_replay {
 }
 
 function zmemoize_reset {
-  unset zmemoize_config zmemoize_defs zmemoize_cache
+
+
+  zmemoize_config=
+  zmemoize_defs=
+  zmemoize_cache=
 
   typeset -g -H -A zmemoize_config
   typeset -g -H -A zmemoize_defs
@@ -92,8 +101,22 @@ function zmemoize_reset {
 }
 
 function zmemoize_clear {
-  unset zmemoize_cache
-  typeset -g -H -A zmemoize_cache
+  local pattern=$1
+  
+  if [[ -n $pattern ]]; then
+    local isdone=0
+    while [[ $isdone == 0 ]]; do
+      key=${zmemoize_cache[(i)$pattern]}
+      if [[ -n $key ]]; then
+        unset "zmemoize_cache[$key]"
+      else
+        isdone=1
+      fi
+    done
+  else
+    unset zmemoize_cache
+    typeset -g -H -A zmemoize_cache
+  fi
 }
 
 
@@ -117,92 +140,111 @@ function _zmemoize_wrapper {
 function zmemoize {
   emulate -L zsh
 
-  local opt usage funcname
+  local opt usage OPTIND OPTARG delete=0 verbose=0 clear=1 action=memoize require_funcname=1
+  local funcname wrappername
+
+  typeset -A memodef
+
+  # defaults
+  memodef[timeout]=90
+  memodef[stderr]=0
+  memodef[vary_pwd]=0
+  memodef[vary_hostname]=0
+  memodef[vary_username]=0
 
   usage='Usage: zmemoize <options> functionname
 Options:
-    -c              Show currently selected theme and parameters
-    -l              List currently available prompt themes
-    -p [<themes>]   Preview given themes (defaults to all)
-    -h [<theme>]    Display help (for given theme)
-    -s <theme>      Set and save theme
-    <theme>         Switch to new theme immediately (changes not saved)
+    -t <seconds> 
+         Memoization timeout -- note that the memoized value is not guaranteed
+         to persist for this period, or indeed for any period as the cache may
+         be flushed
+
+    -c   Clear cache.
+
+    -E
+         Also memoize standard error output.
+         
+    -U   Unmemoize function
+
+    -P   
+         Current working directory ($PWD)
+    -H
+        Hostname.  Set by default. May be disabled with "+h".
+
+    -u
+        Username.  Set by default. May be disabled with "+u".
+    
+    -h  This help.
+    
+    -l  Print a list of memoized functions.
 '
 
-  while getopts "chlps:t:P:" opt; do
+  while getopts "cUEphPt:l" opt; do
     case "$opt" in
-      (h|p)
-        setopt localtraps
-        if [[ -z "$prompt_theme[1]" ]]; then
-          # Not using a prompt theme; save settings
-          local -a psv; psv=($psvar); local -a +h psvar; psvar=($psv) # Ick
-  	local +h PS1=$PS1 PS2=$PS2 PS3=$PS3 PS4=$PS4 RPS1=$RPS1
-  	local precmd_functions preexec_functions
-        else
-          trap 'prompt_${prompt_theme[1]}_setup "${(@)prompt_theme[2,-1]}"' 0
-        fi
-        ;;
-    esac
-    case "$opt" in
-      c) if [[ -n $prompt_theme ]]; then
-           print -n "Current prompt theme"
-           (( $#prompt_theme > 1 )) && print -n " with parameters"
-           print " is:\n  $prompt_theme"
-         else
-           print "Current prompt is not a theme."
-         fi
+      h) print $usage; exit 0 ;;
+      U) delete=1; action=unmemoize ;;
+      c) action=clear; require_funcname=0 ;;
+      E) memodef[stderr]=1 ;;
+      t) memodef[timeout]=$OPTARG ;;
+      p) memodef[vary_hostname]=1 ;;
+      H) memodef[vary_hostname]=1 ;;
+      P) memodef[vary_pwd]=1 ;;
+      v) verbose=1 ;;
+      l) action=list
+         print ${(k)zmemoize_defs}
          return
          ;;
-      h) if [[ -n "$2" && -n $prompt_themes[(r)$2] ]]; then
-           if functions prompt_$2_setup >/dev/null; then
-  	   # The next line is a bit ugly.  It (perhaps unnecessarily)
-  	   # runs the prompt theme setup function to ensure that if
-  	   # the theme has a _help function that it's been autoloaded.
-  	   prompt_$2_setup
-  	 fi
-           if functions prompt_$2_help >/dev/null; then
-             print "Help for $2 theme:\n"
-             prompt_$2_help
-           else
-             print "No help available for $2 theme."
-           fi
-           print "\nType \`prompt -p $2' to preview the theme, \`prompt $2'"
-           print "to try it out, and \`prompt -s $2' to use it in future sessions."
-         else
-           print "$usage"
-         fi
-         ;;
-      l) 
-         print ${(i)zmemoize_defs}
-         return
-         ;;
-      p) preview=( $prompt_themes )
-         (( $#* > 1 )) && preview=( "$@[2,-1]" )
-         for theme in $preview; do
-           [[ "$theme" == "$prompt_theme[*]" ]] && continue
-           prompt_preview_safely "$=theme"
-         done
-         print -P "%b%f%k"
-         ;;
+      *) print $usage; return 1;;
     esac
   done
 
   shift $(( OPTIND - 1 ))
 
-  if (( $# != 1 )); then
+  if [[ $require_funcname == 1 ]] && (( $# != 1 )); then
     print $usage
     return 1
   fi
 
   funcname=$1
   wrappername="_zmemoize_wrapped_$funcname"
-  zctrace "memoizing $funcname to $wrappername"
+
+  case $action in
+    clear)
+        zmemoize_clear $funcname
+      ;;
+    memoize) ;;
+    unmemoize) ;;
+    *) echo "Unknown action: $action" >&2; exit 1;;
+  esac
+
+  # clear all cached bits
+  zmemoize_clear "${funcname}:*"
+
+  # if deletion is requested, or function is already memoized
+  if [[ $delete == 1 || -n $zmemoize_defs[$funcname] ]]; then
+    if [[ -n $zmemoize_defs[$funcname] ]]; then
+      zctrace "unmemoizing $funcname from $wrappername"
+      
+      unfunction $funcname
+      unset "zmemoize_defs[$funcname]"
+      zshellfunc_rename $wrappername $funcname || { echo "FAILED TO RENAME BACK: $?"; return 21 }
+      return 0
+    else
+      [[ $action == "unmemoize" ]] && return 35
+    fi
+  fi
   
-  unfunction $wrappername &>/dev/null
-  zshellfunc_rename $funcname $wrappername || { echo "FAILED TO RENAME: $?"; return 20 }
-  function $funcname {
-    _zmemoize_wrapper $0 $*
-  }
+  if [[ $action == "memoize" ]]; then
+    zctrace "memoizing $funcname to $wrappername"
+  
+    unfunction $wrappername &>/dev/null
+    zshellfunc_rename $funcname $wrappername || { echo "FAILED TO RENAME: $?"; return 20 }
+    function $funcname {
+      _zmemoize_wrapper $0 $*
+    }
+    
+    zmemoize_defs[$funcname]=$(zavp -v memodef)
+  fi
 }
 
 zmemoize_reset
